services:
  fluentd:
    image: fluent/fluentd:v1.18.0-debian-1.0
    volumes:
    - "./fluent.conf:/fluentd/etc/fluent.conf"

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    hostname: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Disable security for testing

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.1
    ports:
      - "5601:5601"
